name: constecon
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0-179.0.dev <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #region core
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.1.2
  retrofit: ^4.0.1
  dio: ^5.2.1+1
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.3.1
  fluro: ^2.0.5
  injectable: ^2.1.2
  get_it: ^7.6.0
  firebase_analytics: ^10.4.3
  firebase_core: ^2.14.0
  firebase_remote_config: ^4.2.3
  firebase_crashlytics: ^3.3.3
  launch_review: ^3.0.1
  package_info_plus: ^4.0.2
  version: ^3.0.2
  flutter_bloc: ^8.1.3
  copy_with_extension: ^5.0.2
  meta: ^1.8.0
  dartz: ^0.10.1
  dotenv: ^4.1.0
  flutter_easyloading: ^3.0.5
  flutter_dotenv: ^5.1.0
  #endregion
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.6
  json_serializable: ^6.6.2
  copy_with_extension_gen: ^5.0.2
  flutter_gen_runner: ^5.3.1
  retrofit_generator: ^7.0.6

flutter_gen:
  output: lib/core/generator
  line_length: 80
  integrations:
    flutter_svg: true
  colors:
    enabled: true
    outputs:
      class_name: AppColors
    inputs:
      - assets/color/colors.xml

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/

    - .env
